# Generated by Django 6.0.3 on 2026-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='for_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='request',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
